### PR TITLE
Table of data with links

### PR DESCRIPTION
**Pull request by brandones**

### CODE REVIEW

**Comment by brandones** [comment]
Screenshot from 2020-03-30 12-13-15

**Comment by brandones** [comment]
@mogoodrich It's passing tests now

**Review by mogoodrich — APPROVED** [review]
It's going to take me a bit until I underestand all of this, but LGTM so far...

**Comment by brandones** [comment]
@mogoodrich Feel free to ask questions in code comments, or here, or in a call... I think it would be worthwhile to build a shared understanding of this code.

**Comment by mogoodrich** [comment]
Makes sense @brandones... I will do more in-depth review and let you know what questions I have...

**Pull request merged**
